apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.operator.installJob.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "knative.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.operator.installJob.serviceAccountName }}
  labels:
    {{- include "knative.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-9"
    "helm.sh/hook-delete-policy": before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ .Values.operator.installJob.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
