//go:build go1.22

// Package vibedhttp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package vibedhttp

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness probe.
	// (GET /healthz)
	Healthz(w http.ResponseWriter, r *http.Request)
	// Prometheus metrics.
	// (GET /metrics)
	Metrics(w http.ResponseWriter, r *http.Request)
	// Readiness probe.
	// (GET /readyz)
	Readyz(w http.ResponseWriter, r *http.Request)
	// List apps owned by the authenticated user.
	// (GET /v1/apps)
	ListApps(w http.ResponseWriter, r *http.Request)
	// Tear down an app.
	// (DELETE /v1/apps/{app_id})
	DeleteApp(w http.ResponseWriter, r *http.Request, appId AppID)
	// Get app status and URL.
	// (GET /v1/apps/{app_id})
	GetApp(w http.ResponseWriter, r *http.Request, appId AppID)
	// Stream logs from the app's runner via SSE.
	// (GET /v1/apps/{app_id}/logs)
	StreamAppLogs(w http.ResponseWriter, r *http.Request, appId AppID)
	// Redeploy with new source.
	// (POST /v1/apps/{app_id}/redeploy)
	RedeployApp(w http.ResponseWriter, r *http.Request, appId AppID)
	// Resume a suspended app, re-claiming compute.
	// (POST /v1/apps/{app_id}/resume)
	ResumeApp(w http.ResponseWriter, r *http.Request, appId AppID)
	// Re-deploy a previous version's retained source.
	// (POST /v1/apps/{app_id}/rollback)
	RollbackApp(w http.ResponseWriter, r *http.Request, appId AppID)
	// Suspend an app, freeing its compute.
	// (POST /v1/apps/{app_id}/suspend)
	SuspendApp(w http.ResponseWriter, r *http.Request, appId AppID)
	// List the app's deploy history (newest first).
	// (GET /v1/apps/{app_id}/versions)
	GetAppVersions(w http.ResponseWriter, r *http.Request, appId AppID)
	// Deploy a new app.
	// (POST /v1/deploy)
	DeployApp(w http.ResponseWriter, r *http.Request)
	// List available runtime templates.
	// (GET /v1/templates)
	ListTemplates(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Healthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Metrics operation middleware
func (siw *ServerInterfaceWrapper) Metrics(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Metrics(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Readyz operation middleware
func (siw *ServerInterfaceWrapper) Readyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Readyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListApps operation middleware
func (siw *ServerInterfaceWrapper) ListApps(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListApps(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApp operation middleware
func (siw *ServerInterfaceWrapper) DeleteApp(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "app_id" -------------
	var appId AppID

	err = runtime.BindStyledParameterWithOptions("simple", "app_id", r.PathValue("app_id"), &appId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "app_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApp(w, r, appId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApp operation middleware
func (siw *ServerInterfaceWrapper) GetApp(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "app_id" -------------
	var appId AppID

	err = runtime.BindStyledParameterWithOptions("simple", "app_id", r.PathValue("app_id"), &appId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "app_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApp(w, r, appId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamAppLogs operation middleware
func (siw *ServerInterfaceWrapper) StreamAppLogs(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "app_id" -------------
	var appId AppID

	err = runtime.BindStyledParameterWithOptions("simple", "app_id", r.PathValue("app_id"), &appId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "app_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamAppLogs(w, r, appId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RedeployApp operation middleware
func (siw *ServerInterfaceWrapper) RedeployApp(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "app_id" -------------
	var appId AppID

	err = runtime.BindStyledParameterWithOptions("simple", "app_id", r.PathValue("app_id"), &appId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "app_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RedeployApp(w, r, appId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResumeApp operation middleware
func (siw *ServerInterfaceWrapper) ResumeApp(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "app_id" -------------
	var appId AppID

	err = runtime.BindStyledParameterWithOptions("simple", "app_id", r.PathValue("app_id"), &appId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "app_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResumeApp(w, r, appId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RollbackApp operation middleware
func (siw *ServerInterfaceWrapper) RollbackApp(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "app_id" -------------
	var appId AppID

	err = runtime.BindStyledParameterWithOptions("simple", "app_id", r.PathValue("app_id"), &appId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "app_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RollbackApp(w, r, appId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SuspendApp operation middleware
func (siw *ServerInterfaceWrapper) SuspendApp(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "app_id" -------------
	var appId AppID

	err = runtime.BindStyledParameterWithOptions("simple", "app_id", r.PathValue("app_id"), &appId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "app_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SuspendApp(w, r, appId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAppVersions operation middleware
func (siw *ServerInterfaceWrapper) GetAppVersions(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "app_id" -------------
	var appId AppID

	err = runtime.BindStyledParameterWithOptions("simple", "app_id", r.PathValue("app_id"), &appId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "app_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAppVersions(w, r, appId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeployApp operation middleware
func (siw *ServerInterfaceWrapper) DeployApp(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeployApp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTemplates operation middleware
func (siw *ServerInterfaceWrapper) ListTemplates(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTemplates(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/healthz", wrapper.Healthz)
	m.HandleFunc("GET "+options.BaseURL+"/metrics", wrapper.Metrics)
	m.HandleFunc("GET "+options.BaseURL+"/readyz", wrapper.Readyz)
	m.HandleFunc("GET "+options.BaseURL+"/v1/apps", wrapper.ListApps)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/apps/{app_id}", wrapper.DeleteApp)
	m.HandleFunc("GET "+options.BaseURL+"/v1/apps/{app_id}", wrapper.GetApp)
	m.HandleFunc("GET "+options.BaseURL+"/v1/apps/{app_id}/logs", wrapper.StreamAppLogs)
	m.HandleFunc("POST "+options.BaseURL+"/v1/apps/{app_id}/redeploy", wrapper.RedeployApp)
	m.HandleFunc("POST "+options.BaseURL+"/v1/apps/{app_id}/resume", wrapper.ResumeApp)
	m.HandleFunc("POST "+options.BaseURL+"/v1/apps/{app_id}/rollback", wrapper.RollbackApp)
	m.HandleFunc("POST "+options.BaseURL+"/v1/apps/{app_id}/suspend", wrapper.SuspendApp)
	m.HandleFunc("GET "+options.BaseURL+"/v1/apps/{app_id}/versions", wrapper.GetAppVersions)
	m.HandleFunc("POST "+options.BaseURL+"/v1/deploy", wrapper.DeployApp)
	m.HandleFunc("GET "+options.BaseURL+"/v1/templates", wrapper.ListTemplates)

	return m
}

type BadRequestJSONResponse Error

type InternalJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type HealthzRequestObject struct {
}

type HealthzResponseObject interface {
	VisitHealthzResponse(w http.ResponseWriter) error
}

type Healthz200Response struct {
}

func (response Healthz200Response) VisitHealthzResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type Healthz503Response struct {
}

func (response Healthz503Response) VisitHealthzResponse(w http.ResponseWriter) error {
	w.WriteHeader(503)
	return nil
}

type MetricsRequestObject struct {
}

type MetricsResponseObject interface {
	VisitMetricsResponse(w http.ResponseWriter) error
}

type Metrics200TextResponse string

func (response Metrics200TextResponse) VisitMetricsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(response))
	return err
}

type ReadyzRequestObject struct {
}

type ReadyzResponseObject interface {
	VisitReadyzResponse(w http.ResponseWriter) error
}

type Readyz200Response struct {
}

func (response Readyz200Response) VisitReadyzResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type Readyz503Response struct {
}

func (response Readyz503Response) VisitReadyzResponse(w http.ResponseWriter) error {
	w.WriteHeader(503)
	return nil
}

type ListAppsRequestObject struct {
}

type ListAppsResponseObject interface {
	VisitListAppsResponse(w http.ResponseWriter) error
}

type ListApps200JSONResponse struct {
	Items []App `json:"items"`
}

func (response ListApps200JSONResponse) VisitListAppsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListApps401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListApps401JSONResponse) VisitListAppsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAppRequestObject struct {
	AppId AppID `json:"app_id"`
}

type DeleteAppResponseObject interface {
	VisitDeleteAppResponse(w http.ResponseWriter) error
}

type DeleteApp204Response struct {
}

func (response DeleteApp204Response) VisitDeleteAppResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteApp401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteApp401JSONResponse) VisitDeleteAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteApp404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteApp404JSONResponse) VisitDeleteAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetAppRequestObject struct {
	AppId AppID `json:"app_id"`
}

type GetAppResponseObject interface {
	VisitGetAppResponse(w http.ResponseWriter) error
}

type GetApp200JSONResponse App

func (response GetApp200JSONResponse) VisitGetAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApp401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetApp401JSONResponse) VisitGetAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetApp404JSONResponse struct{ NotFoundJSONResponse }

func (response GetApp404JSONResponse) VisitGetAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type StreamAppLogsRequestObject struct {
	AppId AppID `json:"app_id"`
}

type StreamAppLogsResponseObject interface {
	VisitStreamAppLogsResponse(w http.ResponseWriter) error
}

type StreamAppLogs200TexteventStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response StreamAppLogs200TexteventStreamResponse) VisitStreamAppLogsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type StreamAppLogs401JSONResponse struct{ UnauthorizedJSONResponse }

func (response StreamAppLogs401JSONResponse) VisitStreamAppLogsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type StreamAppLogs404JSONResponse struct{ NotFoundJSONResponse }

func (response StreamAppLogs404JSONResponse) VisitStreamAppLogsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RedeployAppRequestObject struct {
	AppId AppID `json:"app_id"`
	Body  *multipart.Reader
}

type RedeployAppResponseObject interface {
	VisitRedeployAppResponse(w http.ResponseWriter) error
}

type RedeployApp200JSONResponse DeployResponse

func (response RedeployApp200JSONResponse) VisitRedeployAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RedeployApp202JSONResponse DeployResponse

func (response RedeployApp202JSONResponse) VisitRedeployAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type RedeployApp401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RedeployApp401JSONResponse) VisitRedeployAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type RedeployApp404JSONResponse struct{ NotFoundJSONResponse }

func (response RedeployApp404JSONResponse) VisitRedeployAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ResumeAppRequestObject struct {
	AppId AppID `json:"app_id"`
}

type ResumeAppResponseObject interface {
	VisitResumeAppResponse(w http.ResponseWriter) error
}

type ResumeApp202JSONResponse App

func (response ResumeApp202JSONResponse) VisitResumeAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type ResumeApp401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ResumeApp401JSONResponse) VisitResumeAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ResumeApp404JSONResponse struct{ NotFoundJSONResponse }

func (response ResumeApp404JSONResponse) VisitResumeAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RollbackAppRequestObject struct {
	AppId AppID `json:"app_id"`
	Body  *RollbackAppJSONRequestBody
}

type RollbackAppResponseObject interface {
	VisitRollbackAppResponse(w http.ResponseWriter) error
}

type RollbackApp200JSONResponse DeployResponse

func (response RollbackApp200JSONResponse) VisitRollbackAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RollbackApp202JSONResponse DeployResponse

func (response RollbackApp202JSONResponse) VisitRollbackAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type RollbackApp400JSONResponse Error

func (response RollbackApp400JSONResponse) VisitRollbackAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RollbackApp401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RollbackApp401JSONResponse) VisitRollbackAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type RollbackApp404JSONResponse struct{ NotFoundJSONResponse }

func (response RollbackApp404JSONResponse) VisitRollbackAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type SuspendAppRequestObject struct {
	AppId AppID `json:"app_id"`
}

type SuspendAppResponseObject interface {
	VisitSuspendAppResponse(w http.ResponseWriter) error
}

type SuspendApp202JSONResponse App

func (response SuspendApp202JSONResponse) VisitSuspendAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type SuspendApp401JSONResponse struct{ UnauthorizedJSONResponse }

func (response SuspendApp401JSONResponse) VisitSuspendAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SuspendApp404JSONResponse struct{ NotFoundJSONResponse }

func (response SuspendApp404JSONResponse) VisitSuspendAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetAppVersionsRequestObject struct {
	AppId AppID `json:"app_id"`
}

type GetAppVersionsResponseObject interface {
	VisitGetAppVersionsResponse(w http.ResponseWriter) error
}

type GetAppVersions200JSONResponse struct {
	Items []Version `json:"items"`
}

func (response GetAppVersions200JSONResponse) VisitGetAppVersionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAppVersions401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetAppVersions401JSONResponse) VisitGetAppVersionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetAppVersions404JSONResponse struct{ NotFoundJSONResponse }

func (response GetAppVersions404JSONResponse) VisitGetAppVersionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeployAppRequestObject struct {
	Body *multipart.Reader
}

type DeployAppResponseObject interface {
	VisitDeployAppResponse(w http.ResponseWriter) error
}

type DeployApp200JSONResponse DeployResponse

func (response DeployApp200JSONResponse) VisitDeployAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeployApp202JSONResponse DeployResponse

func (response DeployApp202JSONResponse) VisitDeployAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type DeployApp400JSONResponse struct{ BadRequestJSONResponse }

func (response DeployApp400JSONResponse) VisitDeployAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeployApp401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeployApp401JSONResponse) VisitDeployAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeployApp413JSONResponse Error

func (response DeployApp413JSONResponse) VisitDeployAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)

	return json.NewEncoder(w).Encode(response)
}

type DeployApp500JSONResponse struct{ InternalJSONResponse }

func (response DeployApp500JSONResponse) VisitDeployAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListTemplatesRequestObject struct {
}

type ListTemplatesResponseObject interface {
	VisitListTemplatesResponse(w http.ResponseWriter) error
}

type ListTemplates200JSONResponse struct {
	Items []Template `json:"items"`
}

func (response ListTemplates200JSONResponse) VisitListTemplatesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Liveness probe.
	// (GET /healthz)
	Healthz(ctx context.Context, request HealthzRequestObject) (HealthzResponseObject, error)
	// Prometheus metrics.
	// (GET /metrics)
	Metrics(ctx context.Context, request MetricsRequestObject) (MetricsResponseObject, error)
	// Readiness probe.
	// (GET /readyz)
	Readyz(ctx context.Context, request ReadyzRequestObject) (ReadyzResponseObject, error)
	// List apps owned by the authenticated user.
	// (GET /v1/apps)
	ListApps(ctx context.Context, request ListAppsRequestObject) (ListAppsResponseObject, error)
	// Tear down an app.
	// (DELETE /v1/apps/{app_id})
	DeleteApp(ctx context.Context, request DeleteAppRequestObject) (DeleteAppResponseObject, error)
	// Get app status and URL.
	// (GET /v1/apps/{app_id})
	GetApp(ctx context.Context, request GetAppRequestObject) (GetAppResponseObject, error)
	// Stream logs from the app's runner via SSE.
	// (GET /v1/apps/{app_id}/logs)
	StreamAppLogs(ctx context.Context, request StreamAppLogsRequestObject) (StreamAppLogsResponseObject, error)
	// Redeploy with new source.
	// (POST /v1/apps/{app_id}/redeploy)
	RedeployApp(ctx context.Context, request RedeployAppRequestObject) (RedeployAppResponseObject, error)
	// Resume a suspended app, re-claiming compute.
	// (POST /v1/apps/{app_id}/resume)
	ResumeApp(ctx context.Context, request ResumeAppRequestObject) (ResumeAppResponseObject, error)
	// Re-deploy a previous version's retained source.
	// (POST /v1/apps/{app_id}/rollback)
	RollbackApp(ctx context.Context, request RollbackAppRequestObject) (RollbackAppResponseObject, error)
	// Suspend an app, freeing its compute.
	// (POST /v1/apps/{app_id}/suspend)
	SuspendApp(ctx context.Context, request SuspendAppRequestObject) (SuspendAppResponseObject, error)
	// List the app's deploy history (newest first).
	// (GET /v1/apps/{app_id}/versions)
	GetAppVersions(ctx context.Context, request GetAppVersionsRequestObject) (GetAppVersionsResponseObject, error)
	// Deploy a new app.
	// (POST /v1/deploy)
	DeployApp(ctx context.Context, request DeployAppRequestObject) (DeployAppResponseObject, error)
	// List available runtime templates.
	// (GET /v1/templates)
	ListTemplates(ctx context.Context, request ListTemplatesRequestObject) (ListTemplatesResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Healthz operation middleware
func (sh *strictHandler) Healthz(w http.ResponseWriter, r *http.Request) {
	var request HealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Healthz(ctx, request.(HealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Healthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HealthzResponseObject); ok {
		if err := validResponse.VisitHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Metrics operation middleware
func (sh *strictHandler) Metrics(w http.ResponseWriter, r *http.Request) {
	var request MetricsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Metrics(ctx, request.(MetricsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Metrics")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(MetricsResponseObject); ok {
		if err := validResponse.VisitMetricsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Readyz operation middleware
func (sh *strictHandler) Readyz(w http.ResponseWriter, r *http.Request) {
	var request ReadyzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Readyz(ctx, request.(ReadyzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Readyz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReadyzResponseObject); ok {
		if err := validResponse.VisitReadyzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListApps operation middleware
func (sh *strictHandler) ListApps(w http.ResponseWriter, r *http.Request) {
	var request ListAppsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListApps(ctx, request.(ListAppsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListApps")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAppsResponseObject); ok {
		if err := validResponse.VisitListAppsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteApp operation middleware
func (sh *strictHandler) DeleteApp(w http.ResponseWriter, r *http.Request, appId AppID) {
	var request DeleteAppRequestObject

	request.AppId = appId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteApp(ctx, request.(DeleteAppRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteApp")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteAppResponseObject); ok {
		if err := validResponse.VisitDeleteAppResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApp operation middleware
func (sh *strictHandler) GetApp(w http.ResponseWriter, r *http.Request, appId AppID) {
	var request GetAppRequestObject

	request.AppId = appId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApp(ctx, request.(GetAppRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApp")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAppResponseObject); ok {
		if err := validResponse.VisitGetAppResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StreamAppLogs operation middleware
func (sh *strictHandler) StreamAppLogs(w http.ResponseWriter, r *http.Request, appId AppID) {
	var request StreamAppLogsRequestObject

	request.AppId = appId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StreamAppLogs(ctx, request.(StreamAppLogsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StreamAppLogs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StreamAppLogsResponseObject); ok {
		if err := validResponse.VisitStreamAppLogsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RedeployApp operation middleware
func (sh *strictHandler) RedeployApp(w http.ResponseWriter, r *http.Request, appId AppID) {
	var request RedeployAppRequestObject

	request.AppId = appId

	if reader, err := r.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RedeployApp(ctx, request.(RedeployAppRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RedeployApp")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RedeployAppResponseObject); ok {
		if err := validResponse.VisitRedeployAppResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ResumeApp operation middleware
func (sh *strictHandler) ResumeApp(w http.ResponseWriter, r *http.Request, appId AppID) {
	var request ResumeAppRequestObject

	request.AppId = appId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ResumeApp(ctx, request.(ResumeAppRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ResumeApp")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ResumeAppResponseObject); ok {
		if err := validResponse.VisitResumeAppResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RollbackApp operation middleware
func (sh *strictHandler) RollbackApp(w http.ResponseWriter, r *http.Request, appId AppID) {
	var request RollbackAppRequestObject

	request.AppId = appId

	var body RollbackAppJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RollbackApp(ctx, request.(RollbackAppRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RollbackApp")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RollbackAppResponseObject); ok {
		if err := validResponse.VisitRollbackAppResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SuspendApp operation middleware
func (sh *strictHandler) SuspendApp(w http.ResponseWriter, r *http.Request, appId AppID) {
	var request SuspendAppRequestObject

	request.AppId = appId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SuspendApp(ctx, request.(SuspendAppRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SuspendApp")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SuspendAppResponseObject); ok {
		if err := validResponse.VisitSuspendAppResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAppVersions operation middleware
func (sh *strictHandler) GetAppVersions(w http.ResponseWriter, r *http.Request, appId AppID) {
	var request GetAppVersionsRequestObject

	request.AppId = appId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAppVersions(ctx, request.(GetAppVersionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAppVersions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAppVersionsResponseObject); ok {
		if err := validResponse.VisitGetAppVersionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeployApp operation middleware
func (sh *strictHandler) DeployApp(w http.ResponseWriter, r *http.Request) {
	var request DeployAppRequestObject

	if reader, err := r.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeployApp(ctx, request.(DeployAppRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeployApp")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeployAppResponseObject); ok {
		if err := validResponse.VisitDeployAppResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTemplates operation middleware
func (sh *strictHandler) ListTemplates(w http.ResponseWriter, r *http.Request) {
	var request ListTemplatesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTemplates(ctx, request.(ListTemplatesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTemplates")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTemplatesResponseObject); ok {
		if err := validResponse.VisitListTemplatesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9Ra23IbN9J+la75U2XZ4Ul2kspPXWwpVuJVVo5Ukpy9MLVic6bJQYQBEABDiXbpAfY9",
	"9sn2SbYamOFxKMlZ2crekTMNoNGHr0/zMUl1YbQi5V3S/5gYtFiQJxv+7RtzeMA/hEr6iUGfJ61EYUFJ",
	"P0FjLkWWtBJLv5fCUpb0vS2plbg0pwLjZt6T5aX/eI/tD732/7cvPu62vnt1+1XSSvzM8D7OW6Emye3t",
	"LW/ljFaOwuE/YHZKv5fkPP9LtfKkwk80RooUvdCq+5vTip8tDv3K0jjpJ//XXVysG9+67o/WahuPysil",
	"VhjeJOknh2qKUmRg44Gd5LaVHCpmHuWXOD2eBI7slCwQEwYeftH+J12q7PPzcEpOlzYlUNrDmM8MDLxT",
	"WPpcW/GBvgATb4VzQk1AWxCVRvj4TsKk1erKLoN9WW3IehHtpTLI/sd1y2olEp2/zMhIPaPsEgP7Y20L",
	"/pVk6KntRUGbNlkbe8OW+lqRbXxjcnR0nwhOAhGbfKnC2RvXkajCU1JlkfTfJ2N0PmklE1JkUSYXDcx6",
	"KoxE38Tw7Zxcj36j1DN5aeWKIEorGtxy2cHfL7w+3vKiYduDIOe35DFDj5sXo4kl5+61kUB1oqVIZ7wr",
	"qWkAIk/F/WvV9Fe0yeLOaC3OltW5anZ/LQtUbUuY4UgSMNEevDs9ajscEzhZTiAjK6aUwdjqAoTvJK2k",
	"wJsjUhOfJ/3vXrUawO5iZ456L+pHz//yVZOZLVnBXRc7jWTHU7JWZMF+vJfxQmMsJWvxVa9INgAmkwTn",
	"50cworG2BK50hlTW9rrtFBqXaw87bzRkpQ3+/LxzryEESW5X/2mF5J/kps6jL93lg+zyvzLfJr5XDG7D",
	"RE7IttEY0KUfMTgCSqmv21I434HznCBaNRirb2ZQaaOdkRLk9kArORson5MjyLXzDnaMLB1MxYgOnjlw",
	"M+epiK+eA1oCS5jmbI0dOC6E94yKwsOOtgOFCqgwfgZ8+nMoCJUDpYFuqjASeekMFPvpqvCZa8ouw0mb",
	"tzwg54UKJhCYYSW7FlBn0oFBgkZ0tCGFopPqYpAwTA+SFx26wcJIig/ZcuZOuolQK/7YBEqV726YzVYg",
	"nqIstyDeg+w1BqON81KdNSCF8wEhCkxzoWgBGYG6wUYz8ihkFH2WCd4F5cnSQTFl2mCqIOdw0sBAvgpV",
	"yy/vs/2Kx3rrJlmc1KGrDjonpDLeq5W8liiK+PPMo/Xx5ylhNuNHEVCII8NPKCRljQFqHb82rndsoohA",
	"VyQw1hZ8TpBKdE6MBdkOnFF0iCHHyCGb4bAOfcOBGs0MOkcO+G23fgGOJKW8+x64ej0pb2dGC+WH8xMd",
	"HzdQOCHlnznOP3RGPi5tcqnFHltSj88dxs+XyFdZW5Ht4/C21Q2v0RaXRmt56cSHBs2+Lq0l5YHpgOmA",
	"6Sr1Cgf1pZcij1CeJmSbXbnivsmKfyXrqis3p1Sb4VdLSdnlCNOrS47wS0RzJlpJTJAvc3R5M7ht11sr",
	"Ybt3Hgvz8NxzurjHPRKpKZeP2ZQMX4HS0go/O+OEIgplRGjJ7pc+X/z7qebv57+fbyQTx4cHryHSgddX",
	"pEA4V1IGo1kIaFkbjQAce7IQaKWeCMV6DWkMcxRXL+6ce29iPSDUWDckaOfnJ7B/chjMJQTNVgCFa22v",
	"pMYMtE1zct6i1zYQvSG1f9iOluwpA0asMaaeo+JAccCO5QBwQWMx9SCC4wNv12b+Qh2iqA/Dk+Ozc+hO",
	"d7txyRCK0nmw5EurBupa+Fwo2O2BA/4NJHxOtj9QAC9g+LLXg+O/DeHrsPtYMLi9Oz2CnRyNmQHX1HtL",
	"ToEjp+0oslIVo89bwFG/2u0l7KcpGU8Z74kwXCRNQ/AajJYSrnNSa6gJRqRXLAjeCcBJfR0Ohx2O7i1A",
	"qHJQ8Dl6qKzLASpAN1Pp3EFhVAqZPQ9yPIslox6Dt6XPF948FpJYoqkuOHuhbA/e6Lq8db4cuZDlzPXD",
	"qA0ajWhzlJqQgqlAGBZ4RRBSDiNYmcMOHOhQoVIm/EANzdWkG2wOjeiyFXVfdCakOhM9ZHPMUWURs73w",
	"ki0tGA+bUrLkX8l0F6XJcTcUdvE4zqQ7vc6rJGT2eXCVbk4off6Bf08o4D3DS8iXDjO20+r9WifjZa+3",
	"adMoxTRk8N/2Xm2+zQizFY9N+u8vWokriwLtLOknR2JKqso4RxE1ceIYDLRxyQUv7RbkrUjdVnbfVu+b",
	"2V0q9T3d+K6RKNaK/IYWzlrabHVBPqfSAd0Y7UIGBBH+Onfeb2lldY3mO3IqNNuukdP4+iEKCTttVQgb",
	"XUVxB9d8nLhPLdPdLhqzXS1Hwvl9JrhXL3e3YFaD3zwpf1AJvW9MY76+HHXiRg1xZsMM+EaMEnzt0Fb6",
	"pre7jYP5lbsrvacg9SXrdz7sBvpaxdDDcMf0pDyLhDIoHdllDQShr6ig+zEWhLdR35Ji8F5Vx0F4zgLZ",
	"0Mc3TSUUU2d/9Ja86Jv7F837gqtiOSe0kOlrFWDbmIbbt5pt7g35xhv2Hq3pFyxq0zT2jVlqN35xib2h",
	"YEcQoyigyjg6N8ptuTX+vvm4BUk3ts5vL5qsrSv1ZLv7n3lLWOwbc8RUD8NmmpLybRdWfiJEn4Wg3D7j",
	"5PxH3sZB3IcdVuoJSAa0p9FOFAVz4WLnLTi5Mc8cZyuKbEgTzs5+/NwKsxRzv/URycO3bSVGx0nGqvjf",
	"caVaN+HalpzXlmICV6V2nfrtpaXxkLMqo00pY1qrsliuzrOzHJ165iHNUU047dKcjF4LRzBGKR1wjcN5",
	"IsLYkss5QxRFzJHWI2e8cg0LIRf9QWezNfsrSumFQeu7HNbbdc93WxgqlvrCd8HFWhd5Xn6tlE8jodhQ",
	"7ut8VCubI9Xq+Or2MyLgWme0cQhTDyn2AioJByGBCd73svfyC7JSVxl7saJYVBlPgwS1ZGKJpegaolIf",
	"GN/5gLKasjyq+76WhDaWa67ugQVhETgdSzAuMLWUZMFSO7ibAwwlXzuUfEZnA8WObKktFBumW8K5eM1W",
	"VW5WbWCvK7to9Fu+aWMwf/m5g3k8G4QSXuCTZUEVF7ikETSmNRc/C5H3K/3DzUdLycj5GAa0pq5q5/tg",
	"9lNS/U9vHP0PQGNo0YXw9afHxt7nn5SfL/pDlEGlRpYJ16k4RSHD8OiJ/K9dgTWCsTQVunQ1i5y5kUfB",
	"RdunIXjlzI8P4ackCR0tg+4KOIcky6C9cgy9IjbW5gMPCIPwzkAdqnZBhbazCv4rXRhLoe2V7UGMQQxD",
	"BXqyAqX4QFViW8miAc+rk54G0KvDnxrRazZiVdvi1JViKHSfiuSVHW4vv2Il/GtN9oQ9mHqO8Xh9mAht",
	"kAuuMmZPo8vQulm4WrbCEuwouibnYSys888fv6xbKuMaweBtXc1AaaTGrA8Ikw/CGMrAox2hlKHdzfle",
	"bH57SwRhmo/w89nxLwM1rGucIYykHsXvA9Y68dWwARXFGq4q3/YA1UDRDZuU8DCsevKdxaCzfjIfeDIi",
	"1Qcy6PAG9SwzNOmP0JNKF5OOfmzRk8rC1BLevjs7r9JLWBpmNGHRwZ+1IlxV4haFhT5PVNrOv//5L/i2",
	"B29/CDb2BwvK1oL3P38CddBYWdYdhDCTEg6kmNITZlSgVehNzMdT0XkqjjmezshHzmPyNVArAzB2DgnD",
	"EJP7kS66TfUkfpswZNteZGp3w9jSZ6h/GC53X32BjLAydq81SLQTgh0pCuHnZh4mGw+48Py711XcPqhT",
	"Oi6+13rLFarOQ24NTnfPOM7nVE8YZOdfTzz+tGMuhU7j9KJO0heD1wX9QrQLUV7crk2eVmf37y84xY0j",
	"1hgZN0ZxWZlWXwqFb+fC2N31u3GCuvwZV3LbWl9+pFOUkNF0ZXW/25X8ItfO97/vfd8LeXbF+8fm7ONr",
	"kGJM6SyVNA9C4crVh+WVMW2ywO4MX0OBCicEdCNc+IonDpWWv0t3DYv37xZ3tXgh7QYJVBPXVpgDivhz",
	"aTZZbaH5+Ivb/wQAAP//iY0rLVkvAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
