//go:build go1.22

// Package vibedhttp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package vibedhttp

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness probe.
	// (GET /healthz)
	Healthz(w http.ResponseWriter, r *http.Request)
	// Prometheus metrics.
	// (GET /metrics)
	Metrics(w http.ResponseWriter, r *http.Request)
	// Readiness probe.
	// (GET /readyz)
	Readyz(w http.ResponseWriter, r *http.Request)
	// List apps owned by the authenticated user.
	// (GET /v1/apps)
	ListApps(w http.ResponseWriter, r *http.Request, params ListAppsParams)
	// Tear down an app.
	// (DELETE /v1/apps/{app_id})
	DeleteApp(w http.ResponseWriter, r *http.Request, appId AppID)
	// Get app status and URL.
	// (GET /v1/apps/{app_id})
	GetApp(w http.ResponseWriter, r *http.Request, appId AppID)
	// Stream logs from the app's runner via SSE.
	// (GET /v1/apps/{app_id}/logs)
	StreamAppLogs(w http.ResponseWriter, r *http.Request, appId AppID)
	// Redeploy with new source.
	// (POST /v1/apps/{app_id}/redeploy)
	RedeployApp(w http.ResponseWriter, r *http.Request, appId AppID)
	// Resume a suspended app, re-claiming compute.
	// (POST /v1/apps/{app_id}/resume)
	ResumeApp(w http.ResponseWriter, r *http.Request, appId AppID)
	// Re-deploy a previous version's retained source.
	// (POST /v1/apps/{app_id}/rollback)
	RollbackApp(w http.ResponseWriter, r *http.Request, appId AppID)
	// List an app's share links.
	// (GET /v1/apps/{app_id}/share-links)
	ListShareLinks(w http.ResponseWriter, r *http.Request, appId AppID, params ListShareLinksParams)
	// Mint a public share link for an app.
	// (POST /v1/apps/{app_id}/share-links)
	CreateShareLink(w http.ResponseWriter, r *http.Request, appId AppID)
	// Suspend an app, freeing its compute.
	// (POST /v1/apps/{app_id}/suspend)
	SuspendApp(w http.ResponseWriter, r *http.Request, appId AppID)
	// List the app's deploy history (newest first).
	// (GET /v1/apps/{app_id}/versions)
	GetAppVersions(w http.ResponseWriter, r *http.Request, appId AppID)
	// Deploy a new app.
	// (POST /v1/deploy)
	DeployApp(w http.ResponseWriter, r *http.Request)
	// List available runtime templates.
	// (GET /v1/templates)
	ListTemplates(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Healthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Metrics operation middleware
func (siw *ServerInterfaceWrapper) Metrics(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Metrics(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Readyz operation middleware
func (siw *ServerInterfaceWrapper) Readyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Readyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListApps operation middleware
func (siw *ServerInterfaceWrapper) ListApps(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAppsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListApps(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApp operation middleware
func (siw *ServerInterfaceWrapper) DeleteApp(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "app_id" -------------
	var appId AppID

	err = runtime.BindStyledParameterWithOptions("simple", "app_id", r.PathValue("app_id"), &appId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "app_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApp(w, r, appId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApp operation middleware
func (siw *ServerInterfaceWrapper) GetApp(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "app_id" -------------
	var appId AppID

	err = runtime.BindStyledParameterWithOptions("simple", "app_id", r.PathValue("app_id"), &appId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "app_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApp(w, r, appId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamAppLogs operation middleware
func (siw *ServerInterfaceWrapper) StreamAppLogs(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "app_id" -------------
	var appId AppID

	err = runtime.BindStyledParameterWithOptions("simple", "app_id", r.PathValue("app_id"), &appId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "app_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamAppLogs(w, r, appId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RedeployApp operation middleware
func (siw *ServerInterfaceWrapper) RedeployApp(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "app_id" -------------
	var appId AppID

	err = runtime.BindStyledParameterWithOptions("simple", "app_id", r.PathValue("app_id"), &appId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "app_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RedeployApp(w, r, appId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResumeApp operation middleware
func (siw *ServerInterfaceWrapper) ResumeApp(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "app_id" -------------
	var appId AppID

	err = runtime.BindStyledParameterWithOptions("simple", "app_id", r.PathValue("app_id"), &appId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "app_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResumeApp(w, r, appId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RollbackApp operation middleware
func (siw *ServerInterfaceWrapper) RollbackApp(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "app_id" -------------
	var appId AppID

	err = runtime.BindStyledParameterWithOptions("simple", "app_id", r.PathValue("app_id"), &appId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "app_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RollbackApp(w, r, appId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListShareLinks operation middleware
func (siw *ServerInterfaceWrapper) ListShareLinks(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "app_id" -------------
	var appId AppID

	err = runtime.BindStyledParameterWithOptions("simple", "app_id", r.PathValue("app_id"), &appId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "app_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListShareLinksParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListShareLinks(w, r, appId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateShareLink operation middleware
func (siw *ServerInterfaceWrapper) CreateShareLink(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "app_id" -------------
	var appId AppID

	err = runtime.BindStyledParameterWithOptions("simple", "app_id", r.PathValue("app_id"), &appId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "app_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateShareLink(w, r, appId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SuspendApp operation middleware
func (siw *ServerInterfaceWrapper) SuspendApp(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "app_id" -------------
	var appId AppID

	err = runtime.BindStyledParameterWithOptions("simple", "app_id", r.PathValue("app_id"), &appId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "app_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SuspendApp(w, r, appId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAppVersions operation middleware
func (siw *ServerInterfaceWrapper) GetAppVersions(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "app_id" -------------
	var appId AppID

	err = runtime.BindStyledParameterWithOptions("simple", "app_id", r.PathValue("app_id"), &appId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "app_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAppVersions(w, r, appId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeployApp operation middleware
func (siw *ServerInterfaceWrapper) DeployApp(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeployApp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTemplates operation middleware
func (siw *ServerInterfaceWrapper) ListTemplates(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTemplates(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/healthz", wrapper.Healthz)
	m.HandleFunc("GET "+options.BaseURL+"/metrics", wrapper.Metrics)
	m.HandleFunc("GET "+options.BaseURL+"/readyz", wrapper.Readyz)
	m.HandleFunc("GET "+options.BaseURL+"/v1/apps", wrapper.ListApps)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/apps/{app_id}", wrapper.DeleteApp)
	m.HandleFunc("GET "+options.BaseURL+"/v1/apps/{app_id}", wrapper.GetApp)
	m.HandleFunc("GET "+options.BaseURL+"/v1/apps/{app_id}/logs", wrapper.StreamAppLogs)
	m.HandleFunc("POST "+options.BaseURL+"/v1/apps/{app_id}/redeploy", wrapper.RedeployApp)
	m.HandleFunc("POST "+options.BaseURL+"/v1/apps/{app_id}/resume", wrapper.ResumeApp)
	m.HandleFunc("POST "+options.BaseURL+"/v1/apps/{app_id}/rollback", wrapper.RollbackApp)
	m.HandleFunc("GET "+options.BaseURL+"/v1/apps/{app_id}/share-links", wrapper.ListShareLinks)
	m.HandleFunc("POST "+options.BaseURL+"/v1/apps/{app_id}/share-links", wrapper.CreateShareLink)
	m.HandleFunc("POST "+options.BaseURL+"/v1/apps/{app_id}/suspend", wrapper.SuspendApp)
	m.HandleFunc("GET "+options.BaseURL+"/v1/apps/{app_id}/versions", wrapper.GetAppVersions)
	m.HandleFunc("POST "+options.BaseURL+"/v1/deploy", wrapper.DeployApp)
	m.HandleFunc("GET "+options.BaseURL+"/v1/templates", wrapper.ListTemplates)

	return m
}

type BadRequestJSONResponse Error

type InternalJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type HealthzRequestObject struct {
}

type HealthzResponseObject interface {
	VisitHealthzResponse(w http.ResponseWriter) error
}

type Healthz200Response struct {
}

func (response Healthz200Response) VisitHealthzResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type Healthz503Response struct {
}

func (response Healthz503Response) VisitHealthzResponse(w http.ResponseWriter) error {
	w.WriteHeader(503)
	return nil
}

type MetricsRequestObject struct {
}

type MetricsResponseObject interface {
	VisitMetricsResponse(w http.ResponseWriter) error
}

type Metrics200TextResponse string

func (response Metrics200TextResponse) VisitMetricsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(response))
	return err
}

type ReadyzRequestObject struct {
}

type ReadyzResponseObject interface {
	VisitReadyzResponse(w http.ResponseWriter) error
}

type Readyz200Response struct {
}

func (response Readyz200Response) VisitReadyzResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type Readyz503Response struct {
}

func (response Readyz503Response) VisitReadyzResponse(w http.ResponseWriter) error {
	w.WriteHeader(503)
	return nil
}

type ListAppsRequestObject struct {
	Params ListAppsParams
}

type ListAppsResponseObject interface {
	VisitListAppsResponse(w http.ResponseWriter) error
}

type ListApps200JSONResponse struct {
	Items []App `json:"items"`

	// Total Total number of apps visible to the caller after ownership/authorization filtering, before limit/offset slicing.
	Total *int `json:"total,omitempty"`
}

func (response ListApps200JSONResponse) VisitListAppsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListApps401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListApps401JSONResponse) VisitListAppsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAppRequestObject struct {
	AppId AppID `json:"app_id"`
}

type DeleteAppResponseObject interface {
	VisitDeleteAppResponse(w http.ResponseWriter) error
}

type DeleteApp204Response struct {
}

func (response DeleteApp204Response) VisitDeleteAppResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteApp401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteApp401JSONResponse) VisitDeleteAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteApp404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteApp404JSONResponse) VisitDeleteAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetAppRequestObject struct {
	AppId AppID `json:"app_id"`
}

type GetAppResponseObject interface {
	VisitGetAppResponse(w http.ResponseWriter) error
}

type GetApp200JSONResponse App

func (response GetApp200JSONResponse) VisitGetAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApp401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetApp401JSONResponse) VisitGetAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetApp404JSONResponse struct{ NotFoundJSONResponse }

func (response GetApp404JSONResponse) VisitGetAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type StreamAppLogsRequestObject struct {
	AppId AppID `json:"app_id"`
}

type StreamAppLogsResponseObject interface {
	VisitStreamAppLogsResponse(w http.ResponseWriter) error
}

type StreamAppLogs200TexteventStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response StreamAppLogs200TexteventStreamResponse) VisitStreamAppLogsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type StreamAppLogs401JSONResponse struct{ UnauthorizedJSONResponse }

func (response StreamAppLogs401JSONResponse) VisitStreamAppLogsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type StreamAppLogs404JSONResponse struct{ NotFoundJSONResponse }

func (response StreamAppLogs404JSONResponse) VisitStreamAppLogsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RedeployAppRequestObject struct {
	AppId AppID `json:"app_id"`
	Body  *multipart.Reader
}

type RedeployAppResponseObject interface {
	VisitRedeployAppResponse(w http.ResponseWriter) error
}

type RedeployApp200JSONResponse DeployResponse

func (response RedeployApp200JSONResponse) VisitRedeployAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RedeployApp202JSONResponse DeployResponse

func (response RedeployApp202JSONResponse) VisitRedeployAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type RedeployApp401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RedeployApp401JSONResponse) VisitRedeployAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type RedeployApp404JSONResponse struct{ NotFoundJSONResponse }

func (response RedeployApp404JSONResponse) VisitRedeployAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ResumeAppRequestObject struct {
	AppId AppID `json:"app_id"`
}

type ResumeAppResponseObject interface {
	VisitResumeAppResponse(w http.ResponseWriter) error
}

type ResumeApp202JSONResponse App

func (response ResumeApp202JSONResponse) VisitResumeAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type ResumeApp401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ResumeApp401JSONResponse) VisitResumeAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ResumeApp404JSONResponse struct{ NotFoundJSONResponse }

func (response ResumeApp404JSONResponse) VisitResumeAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RollbackAppRequestObject struct {
	AppId AppID `json:"app_id"`
	Body  *RollbackAppJSONRequestBody
}

type RollbackAppResponseObject interface {
	VisitRollbackAppResponse(w http.ResponseWriter) error
}

type RollbackApp200JSONResponse DeployResponse

func (response RollbackApp200JSONResponse) VisitRollbackAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RollbackApp202JSONResponse DeployResponse

func (response RollbackApp202JSONResponse) VisitRollbackAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type RollbackApp400JSONResponse Error

func (response RollbackApp400JSONResponse) VisitRollbackAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RollbackApp401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RollbackApp401JSONResponse) VisitRollbackAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type RollbackApp404JSONResponse struct{ NotFoundJSONResponse }

func (response RollbackApp404JSONResponse) VisitRollbackAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ListShareLinksRequestObject struct {
	AppId  AppID `json:"app_id"`
	Params ListShareLinksParams
}

type ListShareLinksResponseObject interface {
	VisitListShareLinksResponse(w http.ResponseWriter) error
}

type ListShareLinks200JSONResponse struct {
	Items []ShareLink `json:"items"`

	// Total Total number of share links for the app, before limit/offset slicing.
	Total *int `json:"total,omitempty"`
}

func (response ListShareLinks200JSONResponse) VisitListShareLinksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListShareLinks401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListShareLinks401JSONResponse) VisitListShareLinksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListShareLinks404JSONResponse struct{ NotFoundJSONResponse }

func (response ListShareLinks404JSONResponse) VisitListShareLinksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateShareLinkRequestObject struct {
	AppId AppID `json:"app_id"`
	Body  *CreateShareLinkJSONRequestBody
}

type CreateShareLinkResponseObject interface {
	VisitCreateShareLinkResponse(w http.ResponseWriter) error
}

type CreateShareLink200JSONResponse ShareLink

func (response CreateShareLink200JSONResponse) VisitCreateShareLinkResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateShareLink400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateShareLink400JSONResponse) VisitCreateShareLinkResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateShareLink401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateShareLink401JSONResponse) VisitCreateShareLinkResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateShareLink404JSONResponse struct{ NotFoundJSONResponse }

func (response CreateShareLink404JSONResponse) VisitCreateShareLinkResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type SuspendAppRequestObject struct {
	AppId AppID `json:"app_id"`
}

type SuspendAppResponseObject interface {
	VisitSuspendAppResponse(w http.ResponseWriter) error
}

type SuspendApp202JSONResponse App

func (response SuspendApp202JSONResponse) VisitSuspendAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type SuspendApp401JSONResponse struct{ UnauthorizedJSONResponse }

func (response SuspendApp401JSONResponse) VisitSuspendAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SuspendApp404JSONResponse struct{ NotFoundJSONResponse }

func (response SuspendApp404JSONResponse) VisitSuspendAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetAppVersionsRequestObject struct {
	AppId AppID `json:"app_id"`
}

type GetAppVersionsResponseObject interface {
	VisitGetAppVersionsResponse(w http.ResponseWriter) error
}

type GetAppVersions200JSONResponse struct {
	Items []Version `json:"items"`
}

func (response GetAppVersions200JSONResponse) VisitGetAppVersionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAppVersions401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetAppVersions401JSONResponse) VisitGetAppVersionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetAppVersions404JSONResponse struct{ NotFoundJSONResponse }

func (response GetAppVersions404JSONResponse) VisitGetAppVersionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeployAppRequestObject struct {
	Body *multipart.Reader
}

type DeployAppResponseObject interface {
	VisitDeployAppResponse(w http.ResponseWriter) error
}

type DeployApp200JSONResponse DeployResponse

func (response DeployApp200JSONResponse) VisitDeployAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeployApp202JSONResponse DeployResponse

func (response DeployApp202JSONResponse) VisitDeployAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type DeployApp400JSONResponse struct{ BadRequestJSONResponse }

func (response DeployApp400JSONResponse) VisitDeployAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeployApp401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeployApp401JSONResponse) VisitDeployAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeployApp413JSONResponse Error

func (response DeployApp413JSONResponse) VisitDeployAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)

	return json.NewEncoder(w).Encode(response)
}

type DeployApp500JSONResponse struct{ InternalJSONResponse }

func (response DeployApp500JSONResponse) VisitDeployAppResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListTemplatesRequestObject struct {
}

type ListTemplatesResponseObject interface {
	VisitListTemplatesResponse(w http.ResponseWriter) error
}

type ListTemplates200JSONResponse struct {
	Items []Template `json:"items"`
}

func (response ListTemplates200JSONResponse) VisitListTemplatesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Liveness probe.
	// (GET /healthz)
	Healthz(ctx context.Context, request HealthzRequestObject) (HealthzResponseObject, error)
	// Prometheus metrics.
	// (GET /metrics)
	Metrics(ctx context.Context, request MetricsRequestObject) (MetricsResponseObject, error)
	// Readiness probe.
	// (GET /readyz)
	Readyz(ctx context.Context, request ReadyzRequestObject) (ReadyzResponseObject, error)
	// List apps owned by the authenticated user.
	// (GET /v1/apps)
	ListApps(ctx context.Context, request ListAppsRequestObject) (ListAppsResponseObject, error)
	// Tear down an app.
	// (DELETE /v1/apps/{app_id})
	DeleteApp(ctx context.Context, request DeleteAppRequestObject) (DeleteAppResponseObject, error)
	// Get app status and URL.
	// (GET /v1/apps/{app_id})
	GetApp(ctx context.Context, request GetAppRequestObject) (GetAppResponseObject, error)
	// Stream logs from the app's runner via SSE.
	// (GET /v1/apps/{app_id}/logs)
	StreamAppLogs(ctx context.Context, request StreamAppLogsRequestObject) (StreamAppLogsResponseObject, error)
	// Redeploy with new source.
	// (POST /v1/apps/{app_id}/redeploy)
	RedeployApp(ctx context.Context, request RedeployAppRequestObject) (RedeployAppResponseObject, error)
	// Resume a suspended app, re-claiming compute.
	// (POST /v1/apps/{app_id}/resume)
	ResumeApp(ctx context.Context, request ResumeAppRequestObject) (ResumeAppResponseObject, error)
	// Re-deploy a previous version's retained source.
	// (POST /v1/apps/{app_id}/rollback)
	RollbackApp(ctx context.Context, request RollbackAppRequestObject) (RollbackAppResponseObject, error)
	// List an app's share links.
	// (GET /v1/apps/{app_id}/share-links)
	ListShareLinks(ctx context.Context, request ListShareLinksRequestObject) (ListShareLinksResponseObject, error)
	// Mint a public share link for an app.
	// (POST /v1/apps/{app_id}/share-links)
	CreateShareLink(ctx context.Context, request CreateShareLinkRequestObject) (CreateShareLinkResponseObject, error)
	// Suspend an app, freeing its compute.
	// (POST /v1/apps/{app_id}/suspend)
	SuspendApp(ctx context.Context, request SuspendAppRequestObject) (SuspendAppResponseObject, error)
	// List the app's deploy history (newest first).
	// (GET /v1/apps/{app_id}/versions)
	GetAppVersions(ctx context.Context, request GetAppVersionsRequestObject) (GetAppVersionsResponseObject, error)
	// Deploy a new app.
	// (POST /v1/deploy)
	DeployApp(ctx context.Context, request DeployAppRequestObject) (DeployAppResponseObject, error)
	// List available runtime templates.
	// (GET /v1/templates)
	ListTemplates(ctx context.Context, request ListTemplatesRequestObject) (ListTemplatesResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Healthz operation middleware
func (sh *strictHandler) Healthz(w http.ResponseWriter, r *http.Request) {
	var request HealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Healthz(ctx, request.(HealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Healthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HealthzResponseObject); ok {
		if err := validResponse.VisitHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Metrics operation middleware
func (sh *strictHandler) Metrics(w http.ResponseWriter, r *http.Request) {
	var request MetricsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Metrics(ctx, request.(MetricsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Metrics")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(MetricsResponseObject); ok {
		if err := validResponse.VisitMetricsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Readyz operation middleware
func (sh *strictHandler) Readyz(w http.ResponseWriter, r *http.Request) {
	var request ReadyzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Readyz(ctx, request.(ReadyzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Readyz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReadyzResponseObject); ok {
		if err := validResponse.VisitReadyzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListApps operation middleware
func (sh *strictHandler) ListApps(w http.ResponseWriter, r *http.Request, params ListAppsParams) {
	var request ListAppsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListApps(ctx, request.(ListAppsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListApps")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAppsResponseObject); ok {
		if err := validResponse.VisitListAppsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteApp operation middleware
func (sh *strictHandler) DeleteApp(w http.ResponseWriter, r *http.Request, appId AppID) {
	var request DeleteAppRequestObject

	request.AppId = appId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteApp(ctx, request.(DeleteAppRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteApp")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteAppResponseObject); ok {
		if err := validResponse.VisitDeleteAppResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApp operation middleware
func (sh *strictHandler) GetApp(w http.ResponseWriter, r *http.Request, appId AppID) {
	var request GetAppRequestObject

	request.AppId = appId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApp(ctx, request.(GetAppRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApp")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAppResponseObject); ok {
		if err := validResponse.VisitGetAppResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StreamAppLogs operation middleware
func (sh *strictHandler) StreamAppLogs(w http.ResponseWriter, r *http.Request, appId AppID) {
	var request StreamAppLogsRequestObject

	request.AppId = appId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StreamAppLogs(ctx, request.(StreamAppLogsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StreamAppLogs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StreamAppLogsResponseObject); ok {
		if err := validResponse.VisitStreamAppLogsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RedeployApp operation middleware
func (sh *strictHandler) RedeployApp(w http.ResponseWriter, r *http.Request, appId AppID) {
	var request RedeployAppRequestObject

	request.AppId = appId

	if reader, err := r.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RedeployApp(ctx, request.(RedeployAppRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RedeployApp")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RedeployAppResponseObject); ok {
		if err := validResponse.VisitRedeployAppResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ResumeApp operation middleware
func (sh *strictHandler) ResumeApp(w http.ResponseWriter, r *http.Request, appId AppID) {
	var request ResumeAppRequestObject

	request.AppId = appId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ResumeApp(ctx, request.(ResumeAppRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ResumeApp")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ResumeAppResponseObject); ok {
		if err := validResponse.VisitResumeAppResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RollbackApp operation middleware
func (sh *strictHandler) RollbackApp(w http.ResponseWriter, r *http.Request, appId AppID) {
	var request RollbackAppRequestObject

	request.AppId = appId

	var body RollbackAppJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RollbackApp(ctx, request.(RollbackAppRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RollbackApp")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RollbackAppResponseObject); ok {
		if err := validResponse.VisitRollbackAppResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListShareLinks operation middleware
func (sh *strictHandler) ListShareLinks(w http.ResponseWriter, r *http.Request, appId AppID, params ListShareLinksParams) {
	var request ListShareLinksRequestObject

	request.AppId = appId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListShareLinks(ctx, request.(ListShareLinksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListShareLinks")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListShareLinksResponseObject); ok {
		if err := validResponse.VisitListShareLinksResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateShareLink operation middleware
func (sh *strictHandler) CreateShareLink(w http.ResponseWriter, r *http.Request, appId AppID) {
	var request CreateShareLinkRequestObject

	request.AppId = appId

	var body CreateShareLinkJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateShareLink(ctx, request.(CreateShareLinkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateShareLink")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateShareLinkResponseObject); ok {
		if err := validResponse.VisitCreateShareLinkResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SuspendApp operation middleware
func (sh *strictHandler) SuspendApp(w http.ResponseWriter, r *http.Request, appId AppID) {
	var request SuspendAppRequestObject

	request.AppId = appId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SuspendApp(ctx, request.(SuspendAppRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SuspendApp")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SuspendAppResponseObject); ok {
		if err := validResponse.VisitSuspendAppResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAppVersions operation middleware
func (sh *strictHandler) GetAppVersions(w http.ResponseWriter, r *http.Request, appId AppID) {
	var request GetAppVersionsRequestObject

	request.AppId = appId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAppVersions(ctx, request.(GetAppVersionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAppVersions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAppVersionsResponseObject); ok {
		if err := validResponse.VisitGetAppVersionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeployApp operation middleware
func (sh *strictHandler) DeployApp(w http.ResponseWriter, r *http.Request) {
	var request DeployAppRequestObject

	if reader, err := r.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeployApp(ctx, request.(DeployAppRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeployApp")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeployAppResponseObject); ok {
		if err := validResponse.VisitDeployAppResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTemplates operation middleware
func (sh *strictHandler) ListTemplates(w http.ResponseWriter, r *http.Request) {
	var request ListTemplatesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTemplates(ctx, request.(ListTemplatesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTemplates")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTemplatesResponseObject); ok {
		if err := validResponse.VisitListTemplatesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+Rb3XIbx3J+la6Nq0za+JPkc3ICVipFi7aiE8piiZTPhcAQjd0Gdg5nZ8YzsyAhFaty",
	"m/s8Qp7MT5LqmV1gASz4o1CiU7kiuDs/PT3dX//upyTVhdGKlHfJ8FNi0GJBnmz479CY10f8Q6hkmBj0",
	"edJJFBaUDBM05kJkSSex9FspLGXJ0NuSOolLcyowLuY9WZ767x+w+3HQ/afu+adnnT+/uPkm6SR+YXgd",
	"561Qs+Tm5oaXckYrR2HzHzF7R7+V5Dz/l2rlSYWfaIwUKXqhVf/vTit+ttr0G0vTZJj8Q391sH586/o/",
	"Watt3Cojl1pheJFkmLxWc5QiAxs37CU3neS1YuJRfo3d407gyM7JAvHAQMMv2v+sS5V9eRrekdOlTQmU",
	"9jDlPQMB7xWWPtdWfKSvQMQb4ZxQM9AWRHUjvH0v4aHV7Eoug3xZbch6EeWlEsjhp03J6iQSnb/IyEi9",
	"oOwCA/lTbQv+lWToqetFQdsy2UkKcg5nxBPWSf3XskDVtYQZTiQBXRuJKjAD9BR8TpCW1pLyYHJ01IGp",
	"1UV4/o4wW0CqVSZ4eA/eKkCYopCUQSQSfC4cpGitIAdX+QKEr0fsUW/WA6XhCm0BRmsJU23DyrUmgqfC",
	"SPS0D7//x3+BnnpSYYBWcgGZwJnSTjjAOQrJ5HfACZUS4Gp/9KCIhXFG3gGC0Rnk6HhjqWeuN1Jt7IrY",
	"0HID+kqRbX0T2HOXxJyEQQEhsBK19es4zbX18BILki/RMSt43JIz97yLirlnFfsqcdzvwRtMc6Foed8H",
	"4Dz/3cEGW6ogUFsyKlGFp6TKIhl+SKbofNJJZqTIokzOW9aq77KFeTfL4Xryd0o9Dy+tXJPu0ooWrG2i",
	"9ocVlMe7OG9Z9ijIxRvymKHH7YPRzJJzdyp+GHWipUgXvCqpebAunoq756r5r2iT1ZnRWlw0he5WBeVB",
	"B/D+3XHX4ZTAyXIGGVkxpyyKg/C9pJMUeH1MaubzZPjnF50WC3a+tzRl39WP9v/lmzuk4LaDvYvD3s7J",
	"WpEFKfdexgNNsZR8iy8GRbJlNTJJcHZ2DBOaakvgSmdIZV2vu06hcbn2sPdKQ1bagEv7vTsFIXBy9/W/",
	"q8zzg7DXefSlu7iXXP6vxLeN7jWB2xKRE7JdNAZ06Sds8QCl1FddKZzvwVlOEKUajNXXC6huo5uREuQO",
	"ApiOlM/JEeTaeQd7RpYO5mJCR986cAvnqYiv9gFtAKU0D7ABbwvhPZs64WFP25FCBVQYvwDefR8KQhXA",
	"lq4r3yDSEgFng/lMNWUXYaftUx6R86IyTTyEL9l1ICDdKEEjetqQQtFLdTFK2PaOku96dI2FkRQfsuQs",
	"lXQbodb0sQ2UKt3dEpud5mKOstyBePeS1+hhbO2X6qwFKSKUQ7GB8RBGt8hoRh6FjKzPouFAedLYKPrB",
	"W0Tt9CXydahqvrxL9isa66XbeHFSG9ja6JyQynitTvJSoijiz1OP1sefwSjyowgoxJbh5+B8tBqoTfza",
	"Ot5bE1kEuhqyMssSnRNTQbYHpxQVYsw2csxiOK5N33ikJguDzpEDftuvX4AjSSmvfgCunk/K24XRQvnx",
	"ckfH240Uzkj5bx07lTojH6e2qdRqjR3+5Jc246c5WjoW6nKbnYdgyokUaQd0xVi5AObOlbZZ11jN56IM",
	"pFCX4DWgAjSmtw0b1osppr4C7vVNGP0YGvmWwkKBGQ7Q99pUIrWE/oGudT1n0oLMb9ldhKtcQyEUH6am",
	"o3V3ujbCkqt2X1/pJ363AKGcR+UPACeOHcGIr6J2cqsVePX7EZ+ju6h5vr3p33LyOVmw5LScs1RWOhs8",
	"6Wpa4ygTrSWhig7uXF9S05Q2Xnp9Sar9slJLGSkvUB4AxiuLuxNbJIwRRZjfu8XubtjHIGfgWBbZdVpy",
	"7yonxcYpCiJoK2ZCAYcsWk3FrLSUrbHyPlY8nq2zJpZrQrLB9DWhW/GtDQHPGrq3rgNr530cRd9p0zhe",
	"u+B47cKJjy0w+bKKUVZxHY+rsJIvrzpF4/5YN2Zk2+1iRX0bQ34l66ojt8cn276slpKvAdPLC3aXG4OW",
	"RHSSmEK4yNHl7Z7CbhDsJKxqzmNh7g8h89U57uBIPbK5zTZn+AiUllb4xSl755EpE0JL9rD0+eq/n2v6",
	"/vq3sy3P/O3ro5cQx0WVA+FcSRlMFsE7zLpoBODUk4UwVuqZCHoZYoKg9GH26sy59yZmTISa6pZo5+zs",
	"BA5PXgdxCR5oJ2DmlbaXUmMG2qY5OW/RaxsGvSJ1+LobJZkRttY7djFHiiGlygWkWnmLqWf9DjCsMesy",
	"fSFTo2gI45O3p2fQnz/rxyljKErnwZIvrRqpK+FzoeDZABzwbyDB6DgcKYDvYPx8MIC3/zaG78PqU8Ge",
	"wvt3x7CXozFs2Xx+0FAKnDhtJ26Z8CDn9zvALnS12nM4TFMynjJeE2G8ikDGbA+NljIi2LoLAkakl8wI",
	"XgnASX0VNo9JgQ4gVAFdzI6sEF0BuoVKlwoKk1LIbD/w8TQm1fQUvC19vtLmqZAUEbPgUICyA3il6wSg",
	"8+XEhZBheT/sAoFGI7rs8s1IBVQfF3hJEPx3I/gyxz040iGHR5nwIzU2l7N+kDk0os9S1P+uNyPVm+kx",
	"i2OOKquSGMJLlrQgPCxKSUO/kvkzlCbHZyGXE7fjsLQ36L1IQpicB1Xp54TS5x/594yCOWZ4CcHH64zl",
	"tHq/ket9PhhsyzRKMQ/h8J8GL7bfZoTZmsYmww/nncSVRYF2kQyTYzEnVYVvk4iaOHMMBtq45Jyn9gvy",
	"VqRuJ7lvqvft5DaSoZ6ufd9IFBtp0JYk94aNtbpgZ6F07IRoF/NQEf56t56vMbM6RvsZOa5Y7L6Rd/H1",
	"fS4krLTzQljoqhG3UM3bibuuZf6sj8bsvpZj4fwhD+isFSw+bJL0Bq9FURagymJClrWQl2UQiNhUxeGU",
	"hai3HAxepP8Mg+qlA3YNF8EN3mPDd4U2Y3016AXHaQHLjKWuwVkdYKdSkPIu5FpC0eS3kuxiVTWRohA+",
	"6WxLSMNwbZ7ily3q3aUwddongqZd4i1lwKF6D36hGXoxJwjBdIQTH10mQAeDXSTq6dTRHTSe36kQt1cH",
	"1r2OZWrhXonAQ2PasoBee2zxYc/48aYAzIULN+h1tAEoJdnKIIdMtcuF6deVj3izUyE9sRZ3as6Hu+xH",
	"doGTIhVqdg/nLB6yxfnYwgYW85rmUI35YfBsF3eW19FfK9kEVWxAovORA3zK4I/w+Xk8xw5pkI3SkW2q",
	"ZdDENb3sf4opt5vIbknRo1vX0aPwnC9rS1Z+aEtS8ejsc0/Jk364e9KynLbOljNCC5m+Uo1YeeP0nXYg",
	"ekW+9YSDR6uVBWnfFo1DYxpVuq/OsVcU5AiiawWoMnbZWvm2AdBt262G9GPF+ea8Tdr6Us9224RTxrbi",
	"0JhjHnU/g01zUr7rwswH2u3T4Kl1Tzli+4mXcRDXYYWVesYhOLmnuZ3IilCnW5W60JhvHbuwimzwHU9P",
	"f/rSF2YpBgSbnQX3X7aTGO1a0jrvHTmoyxxdS84zIgevvvL3e/XbC0vTMbvaRptSRvOnspgQXLrsOTr1",
	"rYc0RzVjX1xzhHIlHMEUpXTA9j8k02BqyeUcNogiOs6b7lQ8cg0LIUD5UWeLDfkrSumFQev77Ot166ra",
	"LhNZNCpvt8HFRp1uGZOvxdQToTBY/NszMtXMdku13vVx8wURcKP21Nq7UNf2DwIqCRcLu0H7ng+ef0VS",
	"6tDzIIaZq9DzaZCg5kz0VRVdQbzUe9p33qCs6tiPqr4vJaGNMbyrqwyBWQSu8sm08iHpZMFSN6ibAwx5",
	"gG7IAxidjRQrsqWuUCyYroFz8ZidyieuCm1eV3LRqrd80lZj/vxLG/O4NwglvMAn84IqKrBxI2hMZ8l+",
	"ZiKvV/r7i4+WkpHzMQRo47qqle+C2YeEIQ/PJv4fgMaQtw3m6w+PjYMv32B2tkoaUgbVNTJPlPardqin",
	"0r9uBdYIxtJc6NLVJLLnRh4FB20PQ/BQvOlKoS5vT6csC46fkVSJBaKwxwNzK6FO9QdJrmyc4v91jmVV",
	"fv78TEuTn3XBPxiUr50+aRDyNJod0y6qdk2a5Dxa/LXT0wrSGOrOn9E1ULVNbOWHQF8pF3uklhpRV7qi",
	"+7YsR7c5W5GolZA9lgWvGwGEuqULRYophTIOMlcaDXJV9+coef5DPkr2e3AIoyQbJeDK6VRc89GwMmE8",
	"N8OFW075xyzMaEBe7OYqYtdExdZVV22j4WC7I3ZnX8HyDPUQmKGne227LFcp3daBsLsXZbsx/zE9mAbQ",
	"tORYlpoCVa2/6SncroqNrweeQuXfCOWXOtdQ+YCEO7OM7RY8uuOPH4S9I0noqBk2rYVXIU1i0F6GRhkR",
	"66XLprDYS90bqdeqW1Ch7aIK4CpvylgK1czsAGIUyYFEgZ6sQCk+UpWaqryZFpCodnqakKza/KljspqM",
	"KDEdmFqiGMy6h8ZilSe52wuMuexf62FP6H3U7SltvaWf5wrE4ARy4by2iyf0Alaqlq2RBHuKrsj56Gbu",
	"P35itpGIbQWDN3U+EkojNWZDQJh9FMawZUc7QSnrD1uqD4W8JYLQ8Yzw19O3v4zUuM5SjmEi9ST6BxsN",
	"FlUPCSqKWdgqAXsAqEaKrlmkhIdx1WrRWzWD1k+WTaGMSPWGwTarkar7PUPvxTF6UumqgWUYOy9IZaGZ",
	"Ed68Pz2r3Bdo9Ki0YdHRHzWnu36JOy4sVGripe39/p//DX8awJsf99c69B6WEu6saP/jp0COWnPDdQ0g",
	"tBoJB1LM6QlzIqBVqC4su46i8lQUsz1dkI+Ux/TJSK31NbFySBgHmzyM46LaVE9i//aYZftrelDPXnyF",
	"nE4l7F5rkGhnBHshtFyKeWhYuceBlx98ruP2UZ2UUXS16bdVqLo0uTU43Z5rOVuOekIju2yKfTwrWwfc",
	"Sy70WgPhOs226qdbjV+xdsXK85uNhqL1lswP5+zixs65tnzVidVZmVZfU4Q+59BN6Yb92BjX/NQl2U4Q",
	"HesUJWQ0X5s97Pclv8i188O/DP4yCH52Rfundu/j+xB6potU0tIIhSNXSaFKmLZJYHWG76FAhTMCuhYu",
	"fOkQ20KaH2S7lsmHt7O7mrzidgsHqka6TmjvEvFno+Wszmnx9uc3/xMAAP//1gykzFI+AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
