// Package vibedhttp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package vibedhttp

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for AppRuntimeLane.
const (
	AppRuntimeLaneFast    AppRuntimeLane = "fast"
	AppRuntimeLaneGeneral AppRuntimeLane = "general"
)

// Defines values for Phase.
const (
	Claiming  Phase = "Claiming"
	Failed    Phase = "Failed"
	Pending   Phase = "Pending"
	Ready     Phase = "Ready"
	Starting  Phase = "Starting"
	Suspended Phase = "Suspended"
)

// Defines values for RuntimeOverrideLane.
const (
	RuntimeOverrideLaneFast    RuntimeOverrideLane = "fast"
	RuntimeOverrideLaneGeneral RuntimeOverrideLane = "general"
)

// Defines values for TemplateLane.
const (
	Fast    TemplateLane = "fast"
	General TemplateLane = "general"
)

// App defines model for App.
type App struct {
	AppId          string     `json:"app_id"`
	LastDeployedAt *time.Time `json:"last_deployed_at,omitempty"`

	// Message Human-readable explanation of the current phase, from the Ready condition. On a failed deploy this carries why it failed (e.g. no warm pool for the required template) — often the only diagnosis available, since a deploy that never gets a pod has no logs.
	Message *string `json:"message,omitempty"`
	Name    *string `json:"name,omitempty"`
	Owner   *string `json:"owner,omitempty"`
	Phase   Phase   `json:"phase"`

	// Reason Short CamelCase reason for the current phase, from the Ready condition (e.g. TemplateMissing). Machine-readable; stable.
	Reason  *string `json:"reason,omitempty"`
	Runtime *struct {
		Lane     *AppRuntimeLane `json:"lane,omitempty"`
		Template *string         `json:"template,omitempty"`
	} `json:"runtime,omitempty"`
	Url *string `json:"url,omitempty"`
}

// AppRuntimeLane defines model for App.Runtime.Lane.
type AppRuntimeLane string

// DeployMetadata defines model for DeployMetadata.
type DeployMetadata struct {
	// Egress Per-app outbound allow-list. The egress proxy default-denies; only
	// these hosts (plus vibeD's system hosts) are reachable. Omitting it (or
	// an empty list) means no external egress.
	Egress *EgressPolicy `json:"egress,omitempty"`
	Env    *[]EnvVar     `json:"env,omitempty"`

	// Name Human-readable name; URL-safe slug derived from it.
	Name string `json:"name"`

	// Runtime Optional override for the classifier. Setting `lane` or `template`
	// bypasses lane/template selection; setting `entrypoint` overrides the
	// agent's autodetection.
	Runtime *RuntimeOverride `json:"runtime,omitempty"`

	// Ttl Idle TTL before suspend-to-snapshot (Go duration).
	Ttl *string `json:"ttl,omitempty"`
}

// DeployResponse defines model for DeployResponse.
type DeployResponse struct {
	AppId     string  `json:"app_id"`
	StatusUrl *string `json:"status_url,omitempty"`
	Url       *string `json:"url,omitempty"`
}

// EgressPolicy Per-app outbound allow-list. The egress proxy default-denies; only
// these hosts (plus vibeD's system hosts) are reachable. Omitting it (or
// an empty list) means no external egress.
type EgressPolicy struct {
	// AllowedHosts Destination hostnames, e.g. "api.openai.com" or "*.example.com".
	AllowedHosts *[]string `json:"allowed_hosts,omitempty"`
}

// EnvVar defines model for EnvVar.
type EnvVar struct {
	Name  string  `json:"name"`
	Value *string `json:"value,omitempty"`
}

// Error defines model for Error.
type Error struct {
	// Code stable machine-readable code
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message human-readable description
	Message string `json:"message"`
}

// Phase defines model for Phase.
type Phase string

// RuntimeOverride Optional override for the classifier. Setting `lane` or `template`
// bypasses lane/template selection; setting `entrypoint` overrides the
// agent's autodetection.
type RuntimeOverride struct {
	Entrypoint *string              `json:"entrypoint,omitempty"`
	Lane       *RuntimeOverrideLane `json:"lane,omitempty"`
	Template   *string              `json:"template,omitempty"`
}

// RuntimeOverrideLane defines model for RuntimeOverride.Lane.
type RuntimeOverrideLane string

// ShareLink A public, optionally password-protected link to an app.
type ShareLink struct {
	// ArtifactId The app the link points at.
	ArtifactId string    `json:"artifact_id"`
	CreatedAt  time.Time `json:"created_at"`

	// CreatedBy Owner who minted the link.
	CreatedBy string `json:"created_by"`

	// ExpiresAt Expiry instant; absent means it never expires.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// HasPassword Whether resolving requires a password.
	HasPassword bool `json:"has_password"`
	Revoked     bool `json:"revoked"`

	// Token The credential; a link resolves via this token.
	Token string `json:"token"`

	// Url Public share URL; absent when no public origin is configured.
	Url *string `json:"url,omitempty"`
}

// Template defines model for Template.
type Template struct {
	Description *string      `json:"description,omitempty"`
	Lane        TemplateLane `json:"lane"`
	Name        string       `json:"name"`

	// WarmPoolSize Current warm pool size for this template.
	WarmPoolSize *int `json:"warm_pool_size,omitempty"`
}

// TemplateLane defines model for Template.Lane.
type TemplateLane string

// Version defines model for Version.
type Version struct {
	Lane           *string   `json:"lane,omitempty"`
	RolledBackFrom *int      `json:"rolled_back_from,omitempty"`
	SourceHash     *string   `json:"source_hash,omitempty"`
	Template       *string   `json:"template,omitempty"`
	Timestamp      time.Time `json:"timestamp"`
	Version        int       `json:"version"`
}

// AppID defines model for AppID.
type AppID = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Internal defines model for Internal.
type Internal = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ListAppsParams defines parameters for ListApps.
type ListAppsParams struct {
	// Limit Maximum number of apps to return. Omitted or <= 0 returns every app (backward compatible with pre-pagination clients).
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of apps to skip before the first returned item. Negative values are treated as 0.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// RedeployAppMultipartBody defines parameters for RedeployApp.
type RedeployAppMultipartBody struct {
	Metadata *DeployMetadata    `json:"metadata,omitempty"`
	Source   openapi_types.File `json:"source"`
}

// RollbackAppJSONBody defines parameters for RollbackApp.
type RollbackAppJSONBody struct {
	Version int `json:"version"`
}

// ListShareLinksParams defines parameters for ListShareLinks.
type ListShareLinksParams struct {
	// Limit Maximum number of share links to return. Omitted or <= 0 returns every link (backward compatible with pre-pagination clients).
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of share links to skip before the first returned item. Negative values are treated as 0.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateShareLinkJSONBody defines parameters for CreateShareLink.
type CreateShareLinkJSONBody struct {
	// ExpiresIn Optional lifetime as a Go duration (e.g. "24h"). A "d" suffix is accepted as days (e.g. "7d"). Omitted or empty mints a link that never expires.
	ExpiresIn *string `json:"expires_in,omitempty"`

	// Password Optional password gate. Omitted or empty mints a link that requires no password.
	Password *string `json:"password,omitempty"`
}

// DeployAppMultipartBody defines parameters for DeployApp.
type DeployAppMultipartBody struct {
	Metadata DeployMetadata `json:"metadata"`

	// Source gzipped tarball of the app source (≤ 50 MB).
	Source openapi_types.File `json:"source"`
}

// RedeployAppMultipartRequestBody defines body for RedeployApp for multipart/form-data ContentType.
type RedeployAppMultipartRequestBody RedeployAppMultipartBody

// RollbackAppJSONRequestBody defines body for RollbackApp for application/json ContentType.
type RollbackAppJSONRequestBody RollbackAppJSONBody

// CreateShareLinkJSONRequestBody defines body for CreateShareLink for application/json ContentType.
type CreateShareLinkJSONRequestBody CreateShareLinkJSONBody

// DeployAppMultipartRequestBody defines body for DeployApp for multipart/form-data ContentType.
type DeployAppMultipartRequestBody DeployAppMultipartBody
