// Package vibedhttp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package vibedhttp

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for AppRuntimeLane.
const (
	AppRuntimeLaneFast    AppRuntimeLane = "fast"
	AppRuntimeLaneGeneral AppRuntimeLane = "general"
)

// Defines values for Phase.
const (
	Claiming  Phase = "Claiming"
	Failed    Phase = "Failed"
	Pending   Phase = "Pending"
	Ready     Phase = "Ready"
	Starting  Phase = "Starting"
	Suspended Phase = "Suspended"
)

// Defines values for RuntimeOverrideLane.
const (
	RuntimeOverrideLaneFast    RuntimeOverrideLane = "fast"
	RuntimeOverrideLaneGeneral RuntimeOverrideLane = "general"
)

// Defines values for TemplateLane.
const (
	Fast    TemplateLane = "fast"
	General TemplateLane = "general"
)

// App defines model for App.
type App struct {
	AppId          string     `json:"app_id"`
	LastDeployedAt *time.Time `json:"last_deployed_at,omitempty"`
	Name           *string    `json:"name,omitempty"`
	Owner          *string    `json:"owner,omitempty"`
	Phase          Phase      `json:"phase"`
	Runtime        *struct {
		Lane     *AppRuntimeLane `json:"lane,omitempty"`
		Template *string         `json:"template,omitempty"`
	} `json:"runtime,omitempty"`
	Url *string `json:"url,omitempty"`
}

// AppRuntimeLane defines model for App.Runtime.Lane.
type AppRuntimeLane string

// DeployMetadata defines model for DeployMetadata.
type DeployMetadata struct {
	Env *[]EnvVar `json:"env,omitempty"`

	// Name Human-readable name; URL-safe slug derived from it.
	Name string `json:"name"`

	// Runtime Optional override for the classifier. Setting `lane` or `template`
	// bypasses lane/template selection; setting `entrypoint` overrides the
	// agent's autodetection.
	Runtime *RuntimeOverride `json:"runtime,omitempty"`

	// Ttl Idle TTL before suspend-to-snapshot (Go duration).
	Ttl *string `json:"ttl,omitempty"`
}

// DeployResponse defines model for DeployResponse.
type DeployResponse struct {
	AppId     string  `json:"app_id"`
	StatusUrl *string `json:"status_url,omitempty"`
	Url       *string `json:"url,omitempty"`
}

// EnvVar defines model for EnvVar.
type EnvVar struct {
	Name  string  `json:"name"`
	Value *string `json:"value,omitempty"`
}

// Error defines model for Error.
type Error struct {
	// Code stable machine-readable code
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message human-readable description
	Message string `json:"message"`
}

// Phase defines model for Phase.
type Phase string

// RuntimeOverride Optional override for the classifier. Setting `lane` or `template`
// bypasses lane/template selection; setting `entrypoint` overrides the
// agent's autodetection.
type RuntimeOverride struct {
	Entrypoint *string              `json:"entrypoint,omitempty"`
	Lane       *RuntimeOverrideLane `json:"lane,omitempty"`
	Template   *string              `json:"template,omitempty"`
}

// RuntimeOverrideLane defines model for RuntimeOverride.Lane.
type RuntimeOverrideLane string

// Template defines model for Template.
type Template struct {
	Description *string      `json:"description,omitempty"`
	Lane        TemplateLane `json:"lane"`
	Name        string       `json:"name"`

	// WarmPoolSize Current warm pool size for this template.
	WarmPoolSize *int `json:"warm_pool_size,omitempty"`
}

// TemplateLane defines model for Template.Lane.
type TemplateLane string

// AppID defines model for AppID.
type AppID = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Internal defines model for Internal.
type Internal = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// RedeployAppMultipartBody defines parameters for RedeployApp.
type RedeployAppMultipartBody struct {
	Metadata *DeployMetadata    `json:"metadata,omitempty"`
	Source   openapi_types.File `json:"source"`
}

// DeployAppMultipartBody defines parameters for DeployApp.
type DeployAppMultipartBody struct {
	Metadata DeployMetadata `json:"metadata"`

	// Source gzipped tarball of the app source (≤ 50 MB).
	Source openapi_types.File `json:"source"`
}

// RedeployAppMultipartRequestBody defines body for RedeployApp for multipart/form-data ContentType.
type RedeployAppMultipartRequestBody RedeployAppMultipartBody

// DeployAppMultipartRequestBody defines body for DeployApp for multipart/form-data ContentType.
type DeployAppMultipartRequestBody DeployAppMultipartBody
