# Knative Serving configuration
knative:
  enabled: true
  version: "v1.17.0"
  kourier:
    nodePort: 31080
  domain: "localhost"


sandbox:
  # -- Whether to install agent-sandbox prerequisites (not supported automatically yet, please use kubectl apply from their releases)
  enabled: false
