apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
